version: "3"

services:
    nginx:
        image: nginx:latest
        depends_on:
            - flask
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-net
        ports:
            - 8081:80
    flask:
        build:
            context: .
        networks:
            app-net:
                aliases:
                - flask-app
        volumes:
            - flask-data:/usr/src/app/data
volumes:
    flask-data:
networks:
    app-net:
